# RAG 系统生产环境配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"

# 数据库配置
database:
  driver: "mysql"
  host: "${DB_HOST}"
  port: 3306
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  database: "${DB_DATABASE:pumppill}"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "1h"

# LLM 配置
llm:
  provider: "openai"
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 2048
  options:
    api_key: "${OPENAI_API_KEY}"
    base_url: "${OPENAI_BASE_URL:https://api.openai.com/v1}"
    timeout: "30s"

# 缓存配置
cache:
  type: "redis"
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  database: 0
  schema_ttl: "1h"
  query_result_ttl: "10m"
  max_cache_size: "100MB"

# 日志配置
log:
  level: "error" # 生产环境只记录错误日志
  format: "json"
  output: "file"
  file_path: "/var/log/rag/rag.log"
  max_size: 100
  max_backups: 10
  max_age: 30

# 安全配置
security:
  jwt_secret: "${JWT_SECRET}"
  token_expiry: "24h"
  enable_rbac: true
  allowed_origins:
    - "https://pumppill.com"
    - "https://admin.pumppill.com"

# MCP 配置
mcp:
  host: "0.0.0.0"
  port: 8081
  timeout: "30s"
  max_connections: 1000

# 生产环境特定配置
production:
  enable_debug: false
  enable_profiling: false
  mock_external_services: false
  performance_monitoring: true
  high_availability: true
  auto_scaling: true

# 监控配置
monitoring:
  enable_metrics: true
  metrics_port: 9090
  health_check_interval: "30s"

# 备份配置
backup:
  enable_auto_backup: true
  backup_interval: "6h"
  backup_retention: "7d"
